apiVersion: v1
kind: Pod
metadata:
  name: kube-burner-pod
  namespace: default
spec:
  serviceAccountName: kube-burner-sa
  containers:
    - name: kube-burner-container
      image: jolly3/kube-burner:latest
      imagePullPolicy: Always
      env:
        - name: JOB_ITERATIONS
          value: "10"
        - name: QPS
          value: "100"
        - name: BURST
          value: "100"
        - name: SECRET_REPLICAS
          value: "1000"
        - name: DEPLOYMENT_REPLICAS
          value: "1000"
        - name: SERVICEACCOUNT_REPLICAS
          value: "1000"
        - name: SERVICE_REPLICAS
          value: "1000"
        - name: CONFIGMAP_REPLICAS
          value: "1000"
