apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-burner-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-burner-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-burner-rolebinding
subjects:
- kind: ServiceAccount
  name: kube-burner-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: kube-burner-role
  apiGroup: rbac.authorization.k8s.io
